#!/data/data/com.termux/files/usr/bin/env python3

def _urlstr_filldict(s, d):
    """split str and fill in dict"""
    arr = s.split("&")
    for i in range(len(arr)):
        kv = arr[i].split("=")
        d[kv[0]] = kv[1]

def cgi_entry():
    import sys
    import os
    from urllib.parse import unquote
    method = os.environ["REQUEST_METHOD"]
    path_info = os.environ["PATH_INFO"]
    query_str = unquote(os.environ["QUERY_STRING"])
    content = unquote(sys.stdin.read())
    print("Content-Type: text/html; charset=UTF-8\n")

    pth_arr: list = path_info.strip("/").split("/")
    try:
        m = __import__(pth_arr[0])
        mth = getattr(m, pth_arr[1])
    except Exception as e:
        print(f"ERROR path: {path_info}")

    qs_dict = {}
    _urlstr_filldict(query_str, qs_dict)
    ctx_dict = {}
    _urlstr_filldict(content, ctx_dict)
    mth(qs_dict, ctx_dict)


cgi_entry()
