#!/data/data/com.termux/files/usr/bin/env python3

def _urlstr_filldict(s, d):
    """split str and fill in dict"""
    if s == "":
        return
    arr = s.split("&")
    for i in range(len(arr)):
        kv = arr[i].split("=")
        d[kv[0]] = kv[1]

def cgi_entry():
    import sys
    import os
    from urllib.parse import unquote
    print("Content-Type: text/html; charset=UTF-8\n")

    path_info = os.environ["PATH_INFO"]
    pth_arr: list = path_info.strip("/").split("/")
    try:
        m = __import__(pth_arr[0])
        mth = getattr(m, pth_arr[1])
    except Exception as e:
        print(f"ERROR path: {path_info}, {pth_arr}.\n{e}")
        return

    method = os.environ["REQUEST_METHOD"]
    prm_dict = {}
    try:
        if method == "GET":
            params = unquote(os.environ["QUERY_STRING"])
        else:
            params = unquote(sys.stdin.read())
        _urlstr_filldict(params, prm_dict)
        mth(prm_dict)
    except Exception as e:
        print(e)


cgi_entry()

